// This file is autogenerated by lib/feature-plugin.js
export const methodNames = [
    "avifDecode",
    "jxlDecode",
    "webpDecode",
    "wp2Decode",
    "avifEncode",
    "jxlEncode",
    "mozjpegEncode",
    "oxipngEncode",
    "webpEncode",
    "wp2Encode",
    "rotate",
    "quantize",
    "resize"
];
